var conference_list = [
	{"id": "001", 
	"name": "EGU 2020", 
	"intro": "The EGU General Assembly 2020 will bring together geoscientists from all over the world to one meeting covering all disciplines of the Earth, planetary and space sciences. The EGU aims to provide a forum where scientists, especially early career researchers, can present their work and discuss their ideas with experts in all fields of geoscience. The EGU is looking forward to cordially welcoming you in Vienna.", 
	"url": "https://www.egu2020.eu/", 
	"start_date": "Oct 15, 2019", 
	"end_date": "Jan 15, 2020", 
	"date": "May 03–08, 2020", 
	"year": "2020", 
	"city": "Vienna", 
	"country": "Austria" , 
	"land": "欧洲", 
	"type": "国际", 
	"img": "001"},
	
	{"id": "002", 
	"name": "IGARSS 2020", 
	"intro": "The IGARSS 2020 team is excited to announce a new and more agile format for the Oral Sessions following numerous requests to increase discussion time and foster interactions. For IGARSS 2020, each Oral Session will be composed of 8 papers; a 20-minute, theme oriented introductory talk and 7 short oral presentations of 5 minutes each. Each 5-minute presentation will be associated with a poster presentation in the same room, and there will be 45 minutes at the end of the oral presentations to further discuss the short talks just presented. In cases when the Oral Sessions for the same topic cover more than one time block, the introductory talk will be presented only at the beginning of the first block, and the additional time in the second time block will be allocated to 4 additional 5-minute talks. The format for the interactive Poster Sessions will remain unchanged from the past IGARSS symposia.", 
	"url": "https://igarss2020.org/", 
	"start_date": "Nov 11, 2019", 
	"end_date": "Jan 15, 2020", 
	"date": "Jul 19-24, 2020", 
	"year": "2020", 
	"city": "Hawaii", 
	"country": "USA" , 
	"land": "北美", 
	"type": "国际", 
	"img": "002"},
	
	{"id": "003", 
	"name": "ISPRS 2020", 
	"intro": "The ISPRS Congress is the leading forum where classical and emergent topics related to photogrammetry, remote sensing, and spatial information sciences are discussed. It continues the unique tradition of gathering scientists, educators, and engineers from multiple domains and more than 100 countries. It promotes cross-fertilization between topics and communities, public and private sectors.", 
	"url": "http://www.isprs2020-nice.com/", 
	"start_date": "Nov 18, 2019", 
	"end_date": "Feb 03, 2020", 
	"date": "Jun 14-20, 2020", 
	"year": "2020", 
	"city": "Nice", 
	"country": "France" , 
	"land": "欧洲", 
	"type": "国际", 
	"img": "003"},
	
	{"id": "004", 
	"name": "ICDIP 2020", 
	"intro": "The 12th International Conference on Digital Image Processing (ICDIP 2020) have been held annually in Bangkok (Thailand), Singapore, Chengdu (China) (2011, 2016), Kuala Lumpur (Malaysia), Beijing (China), Athens (Greece), Los Angeles (USA), Hong Kong, Shanghai (China), Guangzhou (China) since 2009. It is one of the leading international conferences for presenting novel and fundamental advances in the fields of Digital Image Processing. Its mission is to foster communication among researchers and practitioners working in a wide variety of scientific areas with a common interest in improving Digital Image Processing related techniques. ICDIP 2020 will feature invited keynotes as well as peer-reviewed paper presentations.The conference is completely open, you will not have to be an author or a discussant to attend. If you do not want paper publication, you can register as oral presentation only. If you do not even have a presentation, you can also participate in the conference by registering as listeners.", 
	"url": "http://www.icdip.org/", 
	"start_date": "", 
	"end_date": "Dec 15, 2019", 
	"date": "May 19-22, 2020", 
	"year": "2020", 
	"city": "Osaka", 
	"country": "Japan" , 
	"land": "亚洲", 
	"type": "国际", 
	"img": "004"}
]


