var data_list = [
	{"id": "001", 
	"name": "全球 1km 分辨率 DEM 数据", 
	"intro": "SRTM数据主要是由美国航空航天局（NASA）和国防部国家测绘局（NIMA)联合测量的，SRTM的全称Shuttle Radar Topography Mission，即航天飞机雷达地形测绘使命。SRTM的数据是用16位的数值表示高程数值的，最大的正高程9000m，负高程海平面以下12000m。本数据格式为IMG格式。", 
	"tags":["DEM", "SRTM", "全球"], 
	"url": "###", 
	"type": "地理", 
	"format": "栅格", 
	"owner": "Yi", 
	"ownerinfo": "SOME INFO ABOUT OWNER", 
	"size": "78.5 MB", 
	"online": "在线", 
	"avatar": "001"},
	
	{"id": "002", 
	"name": "全国 1: 100万 植被图", 
	"intro": "本数据集详细反映了我国11个植被类型组、54个植被型的796个群系和亚群系植被单位的分布状况、水平地带性和垂直地带性分布规律，同时反映了我国2000多个植物优势种、主要农作物和经济作物的实际分布状况及优势种与土壤和地面地质的密切关系。", 
	"tags":["全国", "植被"], 
	"url": "###", 
	"type": "地理", 
	"format": "矢量", 
	"owner": "Yi", 
	"ownerinfo": "SOME INFO ABOUT OWNER", 
	"size": "111 MB", 
	"online": "在线", 
	"avatar": "001"},
	
	{"id": "003", 
	"name": "全球 500m 植被覆盖图", 
	"intro": "该数据采用 2008年 MODIS (Terra & Aqua) 数据制作而成，分辨率为500米，坐标系统为 WGS84。使用该数据请标注\"Geospatial Information Authority of Japan, Chiba University and collaborating organizations\".", 
	"tags":["全球", "植被", "MODIS"], 
	"url": "###", 
	"type": "地理", 
	"format": "栅格", 
	"owner": "Yi", 
	"ownerinfo": "SOME INFO ABOUT OWNER", 
	"size": "442 MB", 
	"online": "在线", 
	"avatar": "001"},
	
	{"id": "004", 
	"name": "遥感场景分类数据集", 
	"intro": " UC Merced Land-Use数据集包括21类场景，每类100张  WHU-RS数据集包括19类场景  每类50张左右", 
	"tags":["遥感", "土地利用", "场景分类"], 
	"url": "###", 
	"type": "遥感", 
	"format": "栅格", 
	"owner": "Wu", 
	"ownerinfo": "SOME INFO ABOUT OWNER", 
	"size": "416 MB", 
	"online": "在线", 
	"avatar": "003"},
	
	{"id": "005", 
	"name": "Image-Net比赛数据集", 
	"intro": "2012年ImageNet比赛所用的数据集，总共1000类", 
	"tags":["Image-Net", "比赛"], 
	"url": "###", 
	"type": "遥感", 
	"format": "栅格", 
	"owner": "Wu", 
	"ownerinfo": "SOME INFO ABOUT OWNER", 
	"size": "137 GB", 
	"online": "离线", 
	"avatar": "003"},
	
	{"id": "006", 
	"name": "ISPRS语义分割比赛数据集", 
	"intro": "ISPRS语义分割比赛POSTAM地区数据集，总共6个地类", 
	"tags":["ISPRS", "语义分割", "比赛"], 
	"url": "###", 
	"type": "遥感", 
	"format": "栅格", 
	"owner": "Wu", 
	"ownerinfo": "SOME INFO ABOUT OWNER", 
	"size": "12.4 GB", 
	"online": "离线", 
	"avatar": "003"},
	
	{"id": "007", 
	"name": "中国国家基础GIS数据", 
	"intro": "包括中国省级、县级行政界线、各级河流水系、主要公路铁路、世界行政边界图等矢量数据，数据生产年份为2010年，比例尺为1: 100万", 
	"tags":["GIS", "矢量", "基础", "全国"], 
	"url": "http: //gaohr.win/site/blogs/2017/2017-04-18-GIS-basic-data-of-China.html", 
	"type": "GIS", 
	"format": "矢量", 
	"owner": "小浪", 
	"ownerinfo": "<a href=\"http: //gaohr.win\" target=\"_blank\">点我查看小浪的信息</a>", 
	"size": "50 MB", 
	"online": "在线", 
	"avatar": "029"}
]